apiVersion: integration/v1
kind: Step
name: query
version: 1
summary: Execute a Postgres query

description: |
  This step executes a query against a Postgres database. The
  results will be set as an output.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/postgres-step-query

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
- summary: Query a Postgres database
  content:
    apiVersion: v1
    kind: Step
    name: postgres-query
    image: relaysh/postgres-step-query
    spec:
      connection:
        url: postgres://my-postgres-host.my-domain.com:5432/my_database?sslmode=disable
      statement: "SELECT name, email_address, phone_number FROM users WHERE created_at BETWEEN '2020-01-01' AND '2020-06-01'"
